### ISSUE TITLE
codeium.nvim cannot read config.json

### ISSUE THREAD

**Issue by zeitchef** [jcdickinson/codeium.nvim#6] opened 2023-01-29 21:52 UTC
I'm getting the following errors from the log:

```
[ERROR Sun Jan 29 22:43:16 2023] ...m/site/pack/packer/start/codeium.nvim/lua/codeium/io.lua:94: could not open  /Users/scott/.cache/nvim/codeium/config.json :  EACCES: permission denied: /Users/scott/.cache/nvim/codeium/config.json
[ERROR Sun Jan 29 22:43:26 2023] ...m/site/pack/packer/start/codeium.nvim/lua/codeium/io.lua:94: could not open  /Users/scott/.cache/nvim/codeium/config.json :  EACCES: permission denied: /Users/scott/.cache/nvim/codeium/config.json
[ERROR Sun Jan 29 22:45:14 2023] ...m/site/pack/packer/start/codeium.nvim/lua/codeium/io.lua:137: could not open  /Users/scott/.cache/nvim/codeium/config.json :  EACCES: permission denied: /Users/scott/.cache/nvim/codeium/config.json
[ERROR Sun Jan 29 22:45:33 2023] ...m/site/pack/packer/start/codeium.nvim/lua/codeium/io.lua:94: could not open  /Users/scott/.cache/nvim/codeium/config.json :  EACCES: permission denied: /Users/scott/.cache/nvim/codeium/config.json
[ERROR Sun Jan 29 22:47:10 2023] ...m/site/pack/packer/start/codeium.nvim/lua/codeium/io.lua:94: could not open  /Users/scott/.cache/nvim/codeium/config.json :  EACCES: permission denied: /Users/scott/.cache/nvim/codeium/config.json
```

**Comment by jcdickinson** [comment] 2023-01-30 00:59
Totally my mistake, I created the file with permissions of `1`! You'll need to fix this by:

```sh
sudo chmod 666 $HOME/.cache/nvim/codeium/config.json
```

Please let me know if that works for you. My most recent commit addresses the issue.

**Comment by jcdickinson** [comment] 2023-01-30 01:00
duplicate of: https://github.com/jcdickinson/codeium.nvim/issues/3

**Closed by jcdickinson** 2023-01-30 01:00 UTC
